version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - java

  - package-ecosystem: gomod
    directory: /control-plane
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /control-plane/api-server
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /control-plane/controller
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /control-plane/scheduler
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /control-plane/catalog
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: gomod
    directory: /control-plane/auth
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - go

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
