{{- if and .Values.console.enabled .Values.console.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "astrasync.componentFullname" (dict "context" . "component" "console") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "astrasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.console.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.console.ingress.className }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  {{- with .Values.console.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.console.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "astrasync.componentFullname" (dict "context" $ "component" "console") }}
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
