{{- if and .Values.console.enabled .Values.console.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astrasync.consoleServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "astrasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- with .Values.console.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
{{- end }}
