{{- if and .Values.connectionTestExecutor.enabled .Values.connectionTestExecutor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "astrasync.connectionTestExecutorServiceAccountName" . }}
  namespace: {{ include "astrasync.connectionTestExecutorNamespace" . }}
  labels:
    {{- include "astrasync.labels" . | nindent 4 }}
    app.kubernetes.io/component: connection-test-executor
  {{- with .Values.connectionTestExecutor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: true
{{- end }}
