package io.astrasync.connector.api;

public enum Capability {
    BATCH_READ,
    STREAM_READ,
    PARALLEL_SNAPSHOT,
    REPLAYABLE_OFFSET,
    SCHEMA_EVOLUTION,
    EXACTLY_ONCE_SOURCE,
    COLUMN_PROJECTION,
    PREDICATE_PUSHDOWN,
    SPLIT_MULTIPLEXING,
    CHANGE_DATA_CAPTURE,
    APPEND,
    UPSERT,
    DELETE,
    TRANSACTIONAL_COMMIT,
    IDEMPOTENT_WRITE,
    BULK_WRITE,
    PARTITION_WRITE,
    SORTED_WRITE,
    SCHEMA_REGISTRATION,
    TRANSFORM_SUPPORT,
    EXACTLY_ONCE,
    AT_LEAST_ONCE,
    AT_MOST_ONCE,
    TRANSACTION_RECOVERY,
    FAULT_TOLERANCE
}
