// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"k8s.io/apimachinery/pkg/runtime"

	"io.astrasync/control-plane/job"
)

func (in *SyncJob) DeepCopyInto(out *SyncJob) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Spec.Source.Options = copyMap(in.Spec.Source.Options)
	out.Spec.Sink.Options = copyMap(in.Spec.Sink.Options)
	if in.Spec.Transforms != nil {
		out.Spec.Transforms = make([]job.TransformSpec, len(in.Spec.Transforms))
		for index := range in.Spec.Transforms {
			out.Spec.Transforms[index] = in.Spec.Transforms[index]
			out.Spec.Transforms[index].Options = copyMap(in.Spec.Transforms[index].Options)
		}
	}
	out.Status = in.Status
	if in.Status.StartTime != nil {
		out.Status.StartTime = in.Status.StartTime.DeepCopy()
	}
	if in.Status.EndTime != nil {
		out.Status.EndTime = in.Status.EndTime.DeepCopy()
	}
	if in.Status.LastCheckpoint != nil {
		checkpoint := *in.Status.LastCheckpoint
		out.Status.LastCheckpoint = &checkpoint
	}
	if in.Status.Failure != nil {
		failure := *in.Status.Failure
		out.Status.Failure = &failure
	}
}

func (in *SyncJob) DeepCopy() *SyncJob {
	if in == nil {
		return nil
	}
	out := new(SyncJob)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncJob) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func (in *SyncJobList) DeepCopyInto(out *SyncJobList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]SyncJob, len(in.Items))
		for index := range in.Items {
			in.Items[index].DeepCopyInto(&out.Items[index])
		}
	}
}

func (in *SyncJobList) DeepCopy() *SyncJobList {
	if in == nil {
		return nil
	}
	out := new(SyncJobList)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncJobList) DeepCopyObject() runtime.Object {
	if copy := in.DeepCopy(); copy != nil {
		return copy
	}
	return nil
}

func copyMap(source map[string]string) map[string]string {
	if source == nil {
		return nil
	}
	result := make(map[string]string, len(source))
	for key, value := range source {
		result[key] = value
	}
	return result
}
